CREATE OR REPLACE NONEDITIONABLE TRIGGER mydwh.TCX_CONFIG_TRG
BEFORE INSERT
ON mydwh.TCX_CONFIG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
  Select mydwh.TCX_CONFIG_SEQ.nextval into n from dual;
  :new.CONFIG_ID := N;
END TCX_CONFIG_TRG;
/