CREATE OR REPLACE NONEDITIONABLE TRIGGER mydwh.TCX_TEAM_PROJECTS_TRG
BEFORE INSERT
ON mydwh.TCX_TEAM_PROJECTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
  Select mydwh.TCX_TEAM_PROJECTS_SEQ.nextval into n from dual;
  :new.PROJECT_ID := N;
END TCX_TEAM_PROJECTS_TRG;
/