CREATE OR REPLACE NONEDITIONABLE TRIGGER mydwh.TCX_OBJECT_HISTORY_TRG
BEFORE INSERT
ON mydwh.TCX_OBJECT_HISTORY
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
  N NUMBER;
BEGIN
-- For Toad:  Highlight column TRANSACTION_ID
  Select mydwh.TCX_OBJECT_HISTORY_SEQ.nextval into n from dual;
  :new.TRANSACTION_ID := N;
END TCX_OBJECT_HISTORY_TRG;
/