CREATE TABLE mydwh.dimemployee (
  employeekey NUMBER(*,0) NOT NULL,
  parentemployeekey NUMBER(*,0),
  employeenationalidalternatekey VARCHAR2(15 BYTE),
  salesterritorykey NUMBER(*,0),
  firstname VARCHAR2(50 BYTE) NOT NULL,
  lastname VARCHAR2(50 BYTE) NOT NULL,
  middlename VARCHAR2(50 BYTE),
  namestyle CHAR NOT NULL,
  title VARCHAR2(50 BYTE),
  hiredate DATE,
  birthdate DATE,
  loginid VARCHAR2(256 BYTE),
  emailaddress VARCHAR2(50 BYTE),
  phone VARCHAR2(25 BYTE),
  maritalstatus NCHAR,
  emergencycontactname VARCHAR2(50 BYTE),
  emergencycontactphone VARCHAR2(25 BYTE),
  salariedflag CHAR,
  gender NCHAR,
  payfrequency NUMBER(*,0),
  baserate NUMBER,
  vacationhours NUMBER(*,0),
  sickleavehours NUMBER(*,0),
  currentflag CHAR NOT NULL,
  salespersonflag CHAR NOT NULL,
  departmentname VARCHAR2(50 BYTE),
  startdate DATE,
  enddate DATE,
  status VARCHAR2(50 BYTE),
  CONSTRAINT "BIN$R+AvYimPRUmY0MJ9oDWdJw==$0" PRIMARY KEY (employeekey) USING INDEX mydwh."BIN$cnpVtNgtQRKUIMXNorf8/A==$0"
);