CREATE TABLE mydwh.dimproduct (
  productkey NUMBER(*,0) NOT NULL,
  productalternatekey VARCHAR2(25 BYTE) NOT NULL,
  productsubcategorykey NUMBER(*,0) NOT NULL,
  weightunitmeasurecode NCHAR(3),
  sizeunitmeasurecode NCHAR(3),
  englishproductname VARCHAR2(50 BYTE) NOT NULL,
  spanishproductname VARCHAR2(50 BYTE) NOT NULL,
  frenchproductname VARCHAR2(50 BYTE) NOT NULL,
  standardcost NUMBER,
  finishedgoodsflag CHAR NOT NULL,
  color VARCHAR2(15 BYTE) NOT NULL,
  safetystocklevel NUMBER(*,0),
  reorderpoint NUMBER(*,0),
  listprice NUMBER,
  psize VARCHAR2(50 BYTE),
  sizerange VARCHAR2(50 BYTE),
  weight FLOAT,
  daystomanufacture NUMBER(*,0),
  productline NCHAR(2),
  dealerprice NUMBER,
  "CLASS" NCHAR(2),
  style NCHAR(2),
  modelname VARCHAR2(50 BYTE),
  largephoto BLOB,
  englishdescription VARCHAR2(400 BYTE),
  frenchdescription VARCHAR2(400 BYTE),
  chinesedescription NVARCHAR2(2000),
  arabicdescription NVARCHAR2(2000),
  hebrewdescription NVARCHAR2(2000),
  thaidescription NVARCHAR2(2000),
  germandescription VARCHAR2(400 BYTE),
  japanesedescription NVARCHAR2(2000),
  turkishdescription NVARCHAR2(2000),
  startdate DATE NOT NULL,
  enddate DATE,
  status VARCHAR2(7 BYTE),
  CONSTRAINT pk_dimproduct_productkey PRIMARY KEY (productkey),
  CONSTRAINT ak_dimproduct_productalternatekey_startdate UNIQUE (productalternatekey,startdate),
  CONSTRAINT fk_dimproduct_dimproductsubcategory FOREIGN KEY (productsubcategorykey) REFERENCES mydwh.dimproductsubcategory (productsubcategorykey)
);